# Generated by Django 5.1 on 2024-10-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_categorias_descripcion_alter_categorias_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='producto'),
        ),
    ]
